/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5f7ab75f-fdb2-4234-bd5c-87817caac86b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_zapQtheG4",
    "aws_user_pools_web_client_id": "2lvdqdns19t173cen2a5e5r731",
    "oauth": {},
    "aws_user_files_s3_bucket": "usecloud-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://u3ux6erxkrabblvmjttd2dizli.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "authenticationFlowType": 'USER_PASSWORD_AUTH',
    "aws_appsync_apiKey": "da2-ioae7kw6gbaelmdylggdpqhsjy"
};


export default awsmobile;
