/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:372aa5bd-6523-40b4-b415-cc77d506f873",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_orYe9nCla",
    "aws_user_pools_web_client_id": "o9004e1rddeavlrji2bl1dafp",
    "oauth": {},
    "aws_user_files_s3_bucket": "usecloudfs716035e194a740d5b72ff7bb29432598194439-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
