/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:eb0c1fd3-b285-4bdf-9a9c-ff5448ea26cf",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_i06GEAvvu",
    "aws_user_pools_web_client_id": "1fbfbpsk8c95rth8jlgn31lq65",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://fnkh2cmd5jatbh2w44cvmkxjmy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
