/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://wtsvu4j6v5bqfm4axply5eec3a.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-1:fdcd8d32-3951-4434-9bac-d250aae2836e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_kULMKeq4Y",
    "aws_user_pools_web_client_id": "5fu1frpof3bah9nju323nn1amn",
    "oauth": {}
};


export default awsmobile;
