
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-06T22:45:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c3136e4250e7e2c53191acccbff8a936479536af",
 "version": "0.14.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
