=name: Lint, Build, and Test

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Run ESLint
      run: yarn check-style
    - name: Run Build
    - run: yarn build
    - name: Run Tests
    - run: yarn test
